name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build + Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add targets
        run: |
          rustup target add aarch64-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu

      - name: Install cross linker for aarch64 (glibc)
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build x86_64
        working-directory: mash-installer
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build aarch64
        working-directory: mash-installer
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu

      - name: Prepare assets
        run: |
          mkdir -p dist
          cp mash-installer/target/x86_64-unknown-linux-gnu/release/mash-installer dist/mash-installer-x86_64
          cp mash-installer/target/aarch64-unknown-linux-gnu/release/mash-installer dist/mash-installer-aarch64
          (cd dist && chmod +x mash-installer-x86_64 mash-installer-aarch64)

          # Dojo bundle as a separate asset
          if [ -d "dojo_bundle" ]; then
            zip -r dist/dojo_bundle.zip dojo_bundle
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/mash-installer-x86_64
            dist/mash-installer-aarch64
            dist/dojo_bundle.zip
